# Generated by Django 2.1.7 on 2024-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('sku', models.CharField(blank=True, max_length=30)),
                ('number', models.IntegerField(max_length=50)),
            ],
        ),
    ]
